version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r .circleci/requirements.txt
      - run: pip install lazy-object-proxy 
      - run: python run.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python tests.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build