version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.9"
      - environment: 
        PORT: 5000
        FLASK_DEBUG: 1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python run.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.9"
    steps:
      - checkout
      - run: python tests.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build